.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
cin2gtab \- converts text input method table to hime's .gtab format
.SH SYNOPSIS
.B cin2gtab
.B [\fB-v\fP|\fB--version\fP]
.br
.SH DESCRIPTION
.B cin2gtab
converts plain text input method table to hime's .gtab binary format.
.SH OPTIONS
.TP
.B \-v, \-\-version
Show version of cin2gtab.
.SH SEE ALSO
.BR hime (1).
.SH AUTHOR
cin2gtab was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
