.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
gtab2cin \- converts gtab input method table to cin table
.SH SYNOPSIS
.B gtab2cin [<file>]
.SH DESCRIPTION
.B gtab2cin
converts from gtab input method table (used by gcin and hime) to cin. If the file path is not provided, the file path will be asked from standard input.
.SH SEE ALSO
.BR hime (1),
.BR hime-setup (1).
.SH AUTHOR
gtab2cin was written by Huang, Kai-Chang (Solomon Huang) <kaichanh@gmail.com>
