.TH HIME 1 "11 JAN 2012" "HIME 0.9" "hime input method platform"
.SH NAME
hime-env \- hime's environment checking tool
.SH SYNOPSIS
.B hime-env
.SH DESCRIPTION
.B hime-env
auto-detect and report system environment, for debugging or bug report.
.SH SEE ALSO
.BR hime (1).
.SH AUTHOR
hime-env was written by Wen-Yen Chuang <caleb AT calno DOT com>
