.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
hime-gtab-merge \- hime's .gtab data merging tool
.SH SYNOPSIS
.B hime-gtab-merge
.SH DESCRIPTION
.B hime-gtab-merge
is used internally only. It is not recommended to call from shells.
.SH SEE ALSO
.BR hime (1).
.SH AUTHOR
hime-gtab-merge was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
