.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
hime-juyin-learn \- show Chinese characters' phonations
.SH SYNOPSIS
.B hime-juyin-learn
.SH DESCRIPTION
.B hime-juyin-learn
displays Chinese characters' phonations in clipboard.
.SH SEE ALSO
.BR hime (1).
.SH AUTHOR
hime-juyin-learn was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
