.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
hime-message \- hime's notification tool
.SH SYNOPSIS
.B hime-message
.B [\fB-icon\fP file]
.B [\fB-text\fP string]
.B [\fB-duration\fP milliseconds]
.SH DESCRIPTION
.B hime-message
displays notification image and/or text. It is useful for filters to have interaction with users.
.SH OPTIONS
.IP "\fB-icon\fP file"
Display an image.
.IP "\fB-text\fP string"
Display text string. The space character is not allowed.
.IP "\fB-duration\fP milliseconds"
Time to show notifications.
.SH SEE ALSO
.BR hime (1).
.SH AUTHOR
hime-message was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
