.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
hime-kbm-toggle \- hime's virtual keyboard toggle tool
.SH SYNOPSIS
.B hime-kbm-toggle
.SH DESCRIPTION
.B hime-kbm-toggle
toggles hime's virtual keyboard.
.SH SEE ALSO
.BR hime (1).
.SH AUTHOR
hime-kbm-toggle was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
