.\"                                      Hey, EMACS: -*- nroff -*-
.TH HIME 1 "29 NOV 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
hime-exit \- send quit message to hime
.SH SYNOPSIS
.B hime-exit
.SH DESCRIPTION
.B hime-exit
sends quit message to hime.  It is used to stop hime server from
scripts.
.PP
.SH SEE ALSO
.BR hime (1),
.br
.SH AUTHOR
hime-exit was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
.PP
This manual page was written by Kan-Ru Chen <koster@debian.org>.
for the Debian project (and may be used by others).
