.TH HIME 1 "2 FEB 2009" "HIME 0.8" "hime input method platform"
.SH NAME
hime-ts-edit \- tsin vocabulary database editor for hime
.SH SYNOPSIS
.B hime-ts-edit
.SH DESCRIPTION
.B hime-ts-edit
is the tsin vocabulary database editor, which you can search and delete the database entries.
.SH SEE ALSO
.BR hime (1),
.BR hime-setup (1),
.BR hime-ts-a2d32 (1),
.BR hime-ts-d2a32 (1),
.BR hime-tsin2gtab-phrase (1),
.BR hime-tslearn (1).
.SH AUTHOR
hime-ts-edit was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
