.TH HIME 1 "21 JAN 2008" "HIME 0.8" "hime input method platform"
.SH NAME
hime-sim2trad, hime-trad2sim \- clipboard data conversion for traditional Chinese and simplified Chinese
.SH SYNOPSIS
.B hime-sim2trad
.br
.B hime-trad2sim
.SH DESCRIPTION
.B hime-sim2trad
converts clipboard's data from simplified Chinese to traditional Chinese.
.PP
.B hime-trad2sim
converts clipboard's data from traditional Chinese to simplified Chinese.
.SH SEE ALSO
.BR hime (1),
.BR hime-gb-toggle (1).
.SH AUTHOR
hime-sim2trad and hime-trad2sim were written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
