#!/bin/bash

for i in sensible-browser x-www-browser xdg-open firefox mozilla-firefox mozilla iceweasel google-chrome chromium opera konqueror icecat midori arora galeon
do
  which $i >& /dev/null
  if [ $? = 0 ]; then
    UTF8ED=$i
    break
  fi
done

export LC_CTYPE=zh_TW.UTF-8
export LC_ALL=zh_TW.UTF-8

if [ -n "$UTF8ED" ]; then
  $UTF8ED $1
fi
