#!/bin/sh
# postinst script for hime

set -e

ua_inst () {
	update-alternatives \
        --install /etc/X11/xinit/xinput.d/$1 xinput-$1 \
        /etc/X11/xinit/xinput.d/$2 $3 ;
}

case "$1" in
    configure)
        # Set up default
        ua_inst all_ALL hime  0
        ua_inst zh_CN   hime 30
        ua_inst zh_TW   hime 50
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
