#!/bin/sh
# prerm script for hime

set -e

ua_remove () {
	update-alternatives \
        --remove xinput-$1 \
        /etc/X11/xinit/xinput.d/$2 ;
}

case "$1" in
    remove|upgrade|deconfigure)
        ua_remove all_ALL hime
        ua_remove zh_CN   hime
        ua_remove zh_TW   hime
	;;
    failed-upgrade)
	;;
    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
   ;;
esac

#DEBHELPER#

exit 0
