name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_archlinux:
    name: Build with Archlinux container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/archlinux

  build_debian:
    name: Build with Debian container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/debian

  build_centos7:
    name: Build with CentOS 7 container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/centos7

  build_centos8:
    name: Build with CentOS 8 container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/centos8

  build_almalinux:
    name: Build with AlmaLinux container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/almalinux
