name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  coding_style:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install \
            clang-format-14 \
            build-essential \
            locales \
            fakeroot \
            devscripts \
            git \
            libxtst-dev \
            libgtk2.0-dev \
            libgtk-3-dev \
            libanthy-dev \
            libchewing3-dev \
            qtbase5-private-dev

      - name: Check with clang-format
        # TODO:
        # The clang-format-14 command should be replaced with make clang-format.
        # However, shell like bash and Github action interpret curly braces differently.
        # This should be fixed with container in the future.
        run: |
          ./configure --disable-qt6-immodule
          clang-format-14 -i \
            src/*.c \
            src/*.h \
            data/*.c \
            src/gtk-im/*.c \
            src/gtk-im/*.h \
            src/im-client/*.c \
            src/im-client/*.h \
            src/modules/*.c \
            src/modules/*.h \
            src/qt5-im/*.h \
            src/qt5-im/*.cpp \
            --verbose
          git --no-pager diff --exit-code

  build_archlinux:
    name: Build with Archlinux container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/archlinux

  build_debian:
    name: Build with Debian container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/debian

  build_centos7:
    name: Build with CentOS 7 container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/centos7

  build_centos8:
    name: Build with CentOS 8 container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/centos8

  build_almalinux:
    name: Build with AlmaLinux container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Docker Action
        uses: ./.github/actions/almalinux
